[package]
name = "blockchain-node"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
blake2 = "0.10.6"
eth_trie = "0.4.0"
jsonrpsee = "0.22.2"
libp2p = "0.53.2"
tokio = "1.36.0"
tracing = "0.1.40"
